### ISSUE TITLE
Que en el home del server se vea públicamente un listado de los jugadores con su ranking actual.

### ISSUE THREAD

**Issue by elsantodel90** [elsantodel90/RAAGo#13]
Es decir, el del evento más reciente. Ordenados de mayor a menor ranking.

Posición Jugador Rating
1             Pepe      4.530
2             Juan      1.235
3             Perez      1.015
4             CasiDan      -1.001
5             Agustín3k      -3.764

Creo que tener 3 decimales en esta vista es algo decente.

**Comment by pignacio** [comment]
Que pasa con los jugadores de los cuales tenemos rating, pero no
participaron en el último evento?
No se muestran y ya?

**Comment by elsantodel90** [comment]
El evento más reciente, de cada jugador ;)

**Comment by elsantodel90** [comment]
En otras palabras, no jugar en un torneo (nuevo, que no esté antes en el tiempo que otros ya existentes) no te cambia el "rating posta" que es el numerito que todos quieren tener y subir.

**Comment by pignacio** [comment]
Claro, groso

2016-06-28 12:22 GMT-03:00 Agustín Santiago Gutiérrez <
notifications@github.com>:

**Comment by elsantodel90** [comment]
Detalle: Solo socios ;)

**Comment by elsantodel90** [comment]
Nota mental: Puede tener muchísimo sentido cachear los ratings para mostrarlos rápido sin ir a la base ni andar buscando "el PlayerRating más reciente para cada jugador" y ordenando.

**Comment by pignacio** [comment]
Acabo de limpiar la tabla de la home para que use las clases CSS de Boostrap,
que son más lindas por default. Igual queda lugar para tunearla

**Comment by elsantodel90** [comment]
Luego de discusión en comisión directiva se implementa un sistema híbrido.

Se deberían mostrar los rankings de "Socios" + los rankings de los no socios que hayan jugado una partida en algún evento "reciente" (probablemente seis meses o un año, a definir).

**Comment by elsantodel90** [comment]
Esto en sí ya está y funciona. Hago un issue nuevo que sea "embellecerlo".
