### ISSUE TITLE
Habría que definir un orden total para los eventos

### ISSUE THREAD

**Issue by pignacio** [elsantodel90/RAAGo#14]
`Event.end_date` está re bien como primera key, pero capaz hay varios que terminan en la misma fecha. Usar el `pk` para desempatar?

Esto importa en cualquier lugar donde ordenemos cosas segun el evento, por ejemplo cuando buscamos el ultimo `mu` y `sigma` de cada jugador para recalcular los ratings.

**Comment by elsantodel90** [comment]
Creo que lo razonable simple y todo terreno es:

Primero por end_date
Luego por start_date
Luego por pk

¿Tiene sentido que sea el orden natural del modelo Event de django no? ¿O no es apropiado usar el orden natural djangoso?

**Comment by pignacio** [comment]
2016-06-29 10:33 GMT-03:00 Agustín Santiago Gutiérrez <
notifications@github.com>:

**Comment by elsantodel90** [comment]
De acuerdo.

**Comment by pignacio** [comment]
Parece que anda!
Notar que los `ORDER BY` son `DESC` porque estoy ordenando por `'-event'`.
i.e. esto devuelve los últimos ratings

```
In [10]: print(PlayerRating.objects.order_by('-event').query)
SELECT "ratings_playerrating"."id", "ratings_playerrating"."player_id", "ratings_playerrating"."event_id", "ratings_playerrating"."mu", "ratings_playerrating"."sigma" FROM "ratings_playerrating" INNER JOIN "events_event" ON ("ratings_playerrating"."event_id" = "events_event"."id") ORDER BY "events_event"."end_date" DESC, "events_event"."start_date" DESC, "events_event"."id" DESC

```
