### ISSUE TITLE
Usabilidad en el admin de Events

### ISSUE THREAD

**Issue by elsantodel90** [elsantodel90/RAAGo#15]
- Los cuadros de texto default son enormes para descripción (tanto de torneo como de partida), que sean de una línea de alto solamente (total se pueden estirar fácilmente en los excepcionales casos en que hace falta).
- El crear "con 3 ítems" ahí listos es demasiado. Yo pondría de hecho cero para PlayerEvents y uno para Games (que haya que pinchar "+ Add another" para PlayerEvents). Motivo del cero / uno: que los PlayerEvents ya no se agregan una vez que terminó la inscripción al torneo, pero los games se siguen agregando hasta que termina el torneo.

**Comment by pignacio** [comment]
Los cuadros de texto de las descripciones se pueden achicar.
Particularmente estoy tentado de no poner la de los juegos, para que el form inline no quede con demasiadas cosas. Que decís?

El resto sale

**Comment by pignacio** [comment]
Levanté una branch [acá](https://github.com/elsantodel90/RAAGo/tree/enhancement-15-usabilidad-en-el-admin-de-events) con las textareas achicadas.
Podemos sacar la description de los games si ocupan mucho espacio
