### ISSUE TITLE
Agregar filtrado de partidos que entran en los ratings y los que no

### ISSUE THREAD

**Issue by pignacio** [elsantodel90/RAAGo#16]
- 0 <= Handicap <= 9
- Si Handicap >= 2, |Komi| < 10
- Si Handicap < 2, |Komi| < 20
- Komi no es entero (es decir, Komi = X.5) [El modelo estadístico asume que el Komi siempre es fraccionario. En realidad el impacto más grande es no preocuparse por los empates nada más... Pero seamos coherentes, total no se juega con Komi entero en torneos]
- El resultado es "Black Wins" o "White Wins", pero el motivo no es WalkOver

**Comment by elsantodel90** [comment]
Parece que existía el QuerySet exacto que hace esto, pero no se estaba usando el QuerySet rated() sino el all() en el task, con lo cual esto no se hacía.
