### ISSUE TITLE
Ver como mandar los partidos correspondientes al "limbo"

### ISSUE THREAD

**Issue by pignacio** [elsantodel90/RAAGo#20]
Esto estaba adentro de #7, pero lo saqué aparte porque no me queda claro como encararlo y lo otro ya estaba re listo.

Una cosa que haría esto bocha mas manejable es no permitir la edicion del `player` ni del `event` para un `EventPlayer` dado. 
Con eso la única situación en la que un cambio rompe el invariante es cuando se borra un `EventPlayer`, y eso es re posible de trackear.

**Comment by elsantodel90** [comment]
Lo que hablamos en la facultad, estoy de acuerdo.
