### ISSUE TITLE
Agregar "información de socio" a los jugadores

### ISSUE THREAD

**Issue by elsantodel90** [elsantodel90/RAAGo#6]
Habría que primero descubrir / entender qué es esa información. Como mínimo, un booleano de si es socio o no.

**Comment by elsantodel90** [comment]
Creo que podemos dar por sentado que la información de socio es simplemente un booleano de si es socio o no.

**Comment by elsantodel90** [comment]
Total es fácil de cambiar.

**Comment by pignacio** [comment]
Nombre para el nuevo field?
`is_member`?

**Comment by elsantodel90** [comment]
Si son todos nombres cipayos, supongo que aago_membership

**Comment by pignacio** [comment]
Es que largamos a programar en cipayo, medio que ya fue.
Prefiero por convención que empiece con `is_`.
`is_aago_member` nos cierra a todos?

**Comment by elsantodel90** [comment]
Sí lo de cipayo me parece perfecto pero no hay que perder la oportunidad de joder, sino sería muy fácil todo.

is_aago_member: Joya (y)

**Comment by elsantodel90** [comment]
Aunque lo bueno de aago_membership es que si deja de ser un booleano algún día en el futuro no hay que cambiarle el nombre (?) Pero me preocuparía cero por eso.

**Comment by pignacio** [comment]
> Aunque lo bueno de aago_membership es que si deja de ser un booleano algún día en el futuro no hay que cambiarle el nombre (?) Pero me preocuparía cero por eso.

Pará, esto puede ser importante.
Si en un futuro puede tomar mas que dos valores ("No socio" / "Socio" / "Presidente" / "BDFL" / etc) yo lo haria de entrada con un `choices` y que ahora tenga solo dos opciones. 
Si hablás de guardar datos sobre la membresia en otro modelo en el futuro es otro tema.

**Comment by elsantodel90** [comment]
Interesante lo de los choices, no lo había pensado. Existen ciertas variantes de socio, aunque creo que no nos afectan en nada para lo que es rating (Por ejemplo el precio de cuota depende de las variables socio estudiante / no estudiante, socio del interior / de CABA). Me parece que si empezamos a guardar más que el bool en algún momento, saltaría de una a tener una tabla de socios como entidad.

**Comment by pignacio** [comment]
Sale boolean `is_aago_member` entonces.
Hacemos algo más con esto que filtrar los ratings de la home?

**Comment by elsantodel90** [comment]
No se me ocurre por ahora. Después si en algún momento lejano hay vistas públicas de un jugador (Lo obvio que se me ocurre: historia de partidas / torneos / gráfico de rating), solo se deberían poder ver los socios. O sea en principio un no socio es invisible salvo a los admines (la primera idea era que ni existan pero esto me parece mucho mejor). Supongo que tiene sentido meter el filtrado este en el modelo porque podría usarse en múltiples lugares.
