### ISSUE TITLE
Agregar y mejorar validación en ABM de games

### ISSUE THREAD

**Issue by elsantodel90** [elsantodel90/RAAGo#7]
La validación de games tiene varias interdependencias:
- La fecha de un partido debería pertenecer al rango de fechas del torneo
- Handicap nunca puede ser 1 (es más que nada para homogeneizar: 1 de handicap es lo mismo que 0, así que usemos siempre 0), y es un entero no negativo.
- Komi solo puede tomar valores enteros o ",5", cualquier otro decimal no tiene sentido alguno y es con probabilidad 1 un error de carga / confunde.
- Agregar resultados "ambos pierden" y "anulado" (ya que la hacemos completa)
- "win_reason" debería depender de result. Por ejemplo "empate" y "abandono" son incompatibles. Habría que ver bien cómo es el cuadrito de opciones.
- Similarmente, "points" necesita un mejor nombre que todavía no encuentro ("victory_margin" o "score_difference" serían mis candidatos). Por otro lado habría que inhabilitarlo si el resultado no es "black wins" / "white wins" o la "reason" no es "points".

**Comment by elsantodel90** [comment]
Otra: Los jugadores deben estar jugando el evento.

**Comment by pignacio** [comment]
> Otra: Los jugadores deben estar jugando el evento.

Lo único que veo delicado con esto es que hacemos con los partidos de un jugador si lo sacamos del evento. Borrarlos suena peligroso, y dejarlos como están rompe el invariante :P

**Comment by elsantodel90** [comment]
Buena observación, deberíamos tener la noción de partidas sueltas (evento NULL ?) entonces, para evitar estos problemas + poder subir partidas que no caen en un evento... A priori esas podrían simplemente no usarse para ranking, pero simplificamos esta operación y hay menos riesgo de perder datos porque sí.

**Comment by pignacio** [comment]
El 28 de junio de 2016, 12:07, Agustín Santiago Gutiérrez <
notifications@github.com> escribió:

> Buena observación, deberíamos tener la noción de partidas sueltas (evento
> NULL ?) entonces, para evitar estos problemas + poder subir partidas que no
> caen en un evento... A priori esas podrían simplemente no usarse para
> ranking, pero simplificamos esta operación y hay menos riesgo de perder
> datos porque sí.

Si, eso se puede hacer desde ahora (aunque el form no te deja (es bug,
btw)).
Se programa, se programa

**Comment by elsantodel90** [comment]
La respuesta a la pregunta de "qué hacemos" sería en ese caso: Les ponemos evento NULL a esos partidos. Codename para el evento NULL: "El Limbo".

**Comment by elsantodel90** [comment]
Otra: points debería ser no negativo.

**Comment by elsantodel90** [comment]
Opciones posibles de 'reason' según 'result':

'black' y 'white' tienen las mismas reason posibles:
    - points
    - resignation
    - timeout
    - walkover
    - other
'draw' tiene las reasons posibles:
    - points
    - other
'both_lose' tiene las reasons posibles:
    - walkover
    - other
'null_match' tiene las reasons posibles:
    - other

Campo "points": Solo debería existir (ser no nulo y estar disponible en la interfaz para cargar) cuando resultado es 'black', 'white' o 'draw', y la reason es 'points' (que puede resumirse en realidad en "la reason es points").

**Comment by pignacio** [comment]
> 'null_match' tiene las reasons posibles:
> - other

Hay que agregar `null_match` como opción, que no lo agregué en #9.

Handicap solo toma valores entero entre 0 y 9 (edit: salvo 1), correcto? Podemos usar un `choices` que te arma una lista descolgable y hace la validación

**Comment by elsantodel90** [comment]
"Lo normal" sería entre 0 y 9, pero nunca 1. ( 0 2 3 4 5 6 7 8 9 )

En realidad podría tomar valores mayores a 9. Pero es súper inusual y excepcional. Pero yo no prohibiría a priori indicar que hubo 13 de handicap. Total handicap mayor a 9 se va a chequear para considerarlo necesariamente unrated.

**Comment by pignacio** [comment]
Agrego: `komi` fraccionario <=> `points` fraccionario

**Comment by elsantodel90** [comment]
Y points también solo puede ser ,5 o entero (medio que se desprende implícito de todo lo anterior pero mejor explicitar).
