### ISSUE TITLE
Agregar campo "exclude" o "unrated" o algo así controlable por un admin

### ISSUE THREAD

**Issue by elsantodel90** [elsantodel90/RAAGo#8]
Por default todo lo que _puede_ ser rateado debería serlo. Para poder marcar algo como rated debería cumplir todas las condiciones:
- 0 <= Handicap <= 9
- Si Handicap >= 2, |Komi| < 10
- Si Handicap < 2, |Komi| < 20
- Komi no es entero (es decir, Komi = X.5) [El modelo estadístico asume que el Komi siempre es fraccionario. En realidad el impacto más grande es no preocuparse por los empates nada más... Pero seamos coherentes, total no se juega con Komi entero en torneos]
- El resultado es "Black Wins" o "White Wins", pero el motivo no es WalkOver

**Comment by pignacio** [comment]
No se si ataría el campo nuevo a todas esas condiciones.
Podemos poner en otro lado de forma más clara la lógica de los partidos que se van a usar para calcular puntajes.
Yo lo veo más como un field que podes poner en `False` si no querés que se use bajo ninguna circunstancia.

**Comment by elsantodel90** [comment]
Sí, me gusta. El campo sería un true / false libre, por defecto false (suponiendo valor "excluded" / "unrated") donde un admin puede indicar explícitamente que un partido no se use.

Después el task que lanza a correr el rating ("el del botón") lo que hace es tomar un partido si vale:

not(excluded(partido)) AND validaciones(partido)

Y si eso no vale saltearlo y tratarlo exactamente igual que si no existiera.

**Comment by elsantodel90** [comment]
Con lo cual este issue se nos estaría partiendo en dos...

1) Agregar el field
2) Cambiar el task de actualización de ratings para que tenga en cuenta el field + validaciones para saltear partidos (y probablemente que deje constancia en el json de los games que se salteó?)

**Comment by pignacio** [comment]
El 29 de junio de 2016, 11:20, Agustín Santiago Gutiérrez <
notifications@github.com> escribió:

> Con lo cual este issue se nos estaría partiendo en dos...
> 
> 1) Agregar el field
> 2) Cambiar el task de actualización de ratings para que tenga en cuenta el
> field + validaciones para saltear partidos (y probablemente que deje
> constancia en el json de los games que se salteó?)
> 
> Una opcion es agregar la opcion '`ranked`' al `QuerySet` de los `Games`,
> porque en el fondo es una lógica de filtrado.
> Capaz una `unranked` también, si hace falta.
> Entonces podés hacer cosas de la pinta:

```
games = event.games  #Esto puede ser cualquier QuerySet de Games
ranked = games.ranked()
unranked = games.unranked()

# ranked y unranked siguen siento querysets, y se puede hacer .filter
.exclude o lo que quieras
```

**Comment by elsantodel90** [comment]
Talibán terminológico: "rated" y "unrated" son los términos apropiados, en lugar de "ranked" y "unranked"

Sí, parece apropiado, y "rated" es algo del dominio de problema así que como filtro es muy razonable que esté ahí. 

De cualquier manera sigue siendo verdad que el task de actualización de ratings tiene que tenerlo en cuenta (pero ahora la forma es simplemente usar el ranked del QuerySet de games de un torneo que está iterando).

**Comment by pignacio** [comment]
> Si, muevo eso a otro issue

El filtrado de rated games es #16
